# These are supported funding model platforms

github: ["https://github.com/Ceoxlex175/Game_Development"]
patreon: ["xlex175"]
thanks_dev: ["@xlex175"]
custom: ["https://github.com/Ceoxlex175/","https://www.facebook.com/@xlex175official"]
